apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: opdata
  name: opdata
  namespace: openproject
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
status: {}
